### ISSUE TITLE
Unable to "apt update" due to Spotify repo

### ISSUE THREAD

**Issue by mrbig033** [AdrianTM/mx-packageinstaller#36]
On MX Linux 17

After using the MX package installer to install Spotify, I got this message which prevented me from performing package operations:

```
Get:3 http://repository.spotify.com stable InRelease [3,302 B]
Err:3 http://repository.spotify.com stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A87FF9DF48BF1C90

```

Commenting out the line `deb http://repository.spotify.com stable non-free` on `/etc/apt/sources.list.d/spotify.list` solved the issue.

**Comment by AdrianTM** [comment]
Thanks, Spotify updated their key, we fixed that in mx-packageinstaller-list it should show up in repos soon, if you want to fix without reinstalling the package you can get the new key with this command:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90`
And uncomment the repo.
