### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by joack** [AdrianTM/mx-packageinstaller#39]
Hello, I'm trying to use the app and I get the following error, no matter if I run it with my user or the root one, it always get the same error. I'm using MX Linux (MX-23.3 “Libretto”)

Joack@Joack-MX:/
$ mx-packageinstaller
mx-packageinstaller version: 24.6.02
+++ void MainWindow::setProgressDialog() +++
+++ void MainWindow::setup() +++
dpkg-query -f '${Version}' -W flatpak
apt-get update --print-uris | grep -m1 -qE '/mx/testrepo/dists/bookworm/test/'
+++ void MainWindow::loadPmFiles() +++
+++ void MainWindow::refreshPopularApps() +++
+++ QStringList MainWindow::listInstalled() const +++
+++ void MainWindow::displayPopularApps() const +++
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by AdrianTM** [comment]
Do you run out of memory? How much free RAM do you have? 
Did it work before? Did you do something relevant before it stopped working? (like adding a repo, broke a package, etc). 

Do regular APT command still work "sudo apt update", "sudo apt upgrade" or do you get errors?

**Comment by joack** [comment]
Hi @AdrianTM:

> Do you run out of memory? 

No, I have a lot of free memory.


> How much free RAM do you have?

16Gb of RAM 


> Did it work before?

It's a fresh install.


> Did you do something relevant before it stopped working? 

Nothing special, I just made an apt update and upgrade after finishing the OS installation.


> Do regular APT command still work "sudo apt update", "sudo apt upgrade" or do you get errors?

It is working fine without errors

**Comment by AdrianTM** [comment]
Not sure what's going on, I don't see this error on my machines and haven't seen anybody mention this on the forum. By the way, it might be worth posting on the forum in case somebody else has an idea about this.

**Comment by joack** [comment]
No worries, I will try to do that. Anyways thanks for the help!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
